from __future__ import annotations

TABLE_SCHEMAS = {
    "md_candidate_manifest": ["md_candidate_id","molecule_id","source","parent_molecule_id","candidate_origin_stage","standard_smiles","prepared_smiles","best_pose_id","receptor_id","receptor_state","protein_ligand_complex_file","ligand_file","receptor_file","stage8_candidate_score","stage9_acceptance_tier","stage10_strategy_name","pose_confidence","gnina_cnnscore","key_interaction_recall_consensus","novelty_bucket","selected_for_quick_md","selected_for_replicate_md","selection_reason","warnings_json"],
    "ligand_parameterization": ["md_candidate_id","molecule_id","ligand_smiles","ligand_input_file","ligand_protonation_state_id","ligand_tautomer_state_id","cgenff_str_file","cgenff_version","cgenff_penalty_max","cgenff_penalty_mean","cgenff_penalty_status","charmm2gmx_status","ligand_itp_file","ligand_prm_file","ligand_gro_file","parameterization_status","rejection_reason","warnings_json"],
    "ligand_parameterization_report": ["ligand_id","molecule_id","backend","input_ligand_file","output_itp","output_gro","net_charge","charge_model","ligand_forcefield","protein_forcefield","water_model","ambertools_version","acpype_version","gromacs_version","parameterization_status","warnings_json"],
    "system_builds": ["md_system_id","md_candidate_id","protein_file","ligand_file","complex_file","topology_file","position_restraints_file","boxed_structure_file","solvated_structure_file","ionized_structure_file","water_model","box_type","box_padding_nm","num_protein_atoms","num_ligand_atoms","num_waters","num_na","num_cl","net_charge_before_ions","final_charge","salt_concentration_molar","build_status","warnings_json"],
    "md_runs": ["md_run_id","md_system_id","md_candidate_id","replicate_id","md_phase","ensemble","input_structure","topology_file","mdp_file","tpr_file","output_structure","trajectory_file","energy_file","log_file","checkpoint_file","gromacs_version","command_line_grompp","command_line_mdrun","start_time","end_time","runtime_seconds","gpu_used_flag","exit_code","run_status","error_message","warnings_json"],
    "equilibration_qc": ["md_system_id","md_candidate_id","replicate_id","minimization_status","final_em_potential_energy","final_em_fmax","nvt_temperature_mean","nvt_temperature_std","npt_temperature_mean","npt_pressure_mean","npt_pressure_std","npt_density_mean","npt_density_std","box_volume_stable_flag","equilibration_pass_flag","failure_reason","warnings_json"],
    "md_metrics": ["md_candidate_id","md_system_id","replicate_id","production_type","trajectory_file","analyzed_ns","ligand_rmsd_median_angstrom","ligand_rmsd_p95_angstrom","ligand_rmsd_max_angstrom","pocket_rmsd_median_angstrom","pocket_rmsd_p95_angstrom","protein_backbone_rmsd_median_angstrom","ligand_com_drift_median_angstrom","ligand_com_drift_max_angstrom","ligand_rg_median_angstrom","fraction_frames_inside_pocket","ligand_left_pocket_flag","ligand_flip_flag","trajectory_analysis_status","warnings_json"],
    "md_interaction_persistence": ["md_candidate_id","md_system_id","replicate_id","key_interaction_id","residue_name","uniprot_residue_number","klifs_position","residue_role","interaction_type","initial_pose_present_flag","consensus_key_interaction_flag","occupancy_fraction","mean_distance","median_distance","persistence_status","warnings_json"],
    "md_binding_mode_persistence": ["md_candidate_id","md_system_id","replicate_id","ifp_tanimoto_to_initial_median","ifp_tanimoto_to_consensus_median","key_interaction_occupancy_mean","key_interaction_occupancy_min","hinge_interaction_occupancy","gatekeeper_region_persistence","dfg_region_persistence","binding_mode_persistence_score","binding_mode_preserved_flag","warnings_json"],
    "md_pose_stability_labels": ["md_candidate_id","molecule_id","source","best_pose_id","replicate_id","md_stability_label","md_stability_score","ligand_rmsd_component","pocket_stability_component","interaction_persistence_component","pocket_retention_component","binding_mode_preserved_flag","ligand_left_pocket_flag","md_acceptance_flag","md_rejection_reason","warnings_json"],
    "md_candidate_summary": ["md_candidate_id","molecule_id","source","parent_molecule_id","num_replicates_completed","num_replicates_stable","num_replicates_moderately_stable","num_replicates_unstable","replicate_success_fraction","median_md_stability_score","min_md_stability_score","median_ligand_rmsd","median_key_interaction_occupancy","median_binding_mode_persistence_score","final_md_label","final_md_decision","final_md_reason","recommended_for_final_dossier","warnings_json"],
    "stage10_post_md_input": ["analog_id","md_candidate_id","molecule_id","parent_molecule_id","strategy_name","source","pre_md_accepted_flag","final_md_label","final_md_decision","md_stability_score","binding_mode_persistence_score","key_interaction_occupancy_mean","ligand_left_pocket_flag","accepted_post_md_flag","post_md_rejection_reason","warnings_json"],
}
